players:
  - name: Human
    type: human
  - name: AI1
    type: ai1
  - name: AI2
    type: ai2
  - name: MCTS
    type: mcts
    data:
      iterations: 32
      expl_const: 0.3
      width: 10000000000
      limit: 10000000000
      heuristic:
        draw_then_smallest_tuple
init_cards: 5
suits:
  - name: HEART
    symbol: ğŸ§¡
    numeric: 1
  - name: BELL
    symbol: ğŸŸ¡
    numeric: 2
  - name: ACORN
    symbol: â™§
    numeric: 3
  - name: LEAF
    symbol: ğŸ‚
    numeric: 4
values:
  - name: VII
    symbol: "7"
    numeric: 7
  - name: VIII
    symbol: "8"
    numeric: 8
  - name: IX
    symbol: "9"
    numeric: 9
  - name: X
    symbol: "10"
    numeric: 10
  - name: UNDER
    symbol: â››
    numeric: 11
  - name: OVER
    symbol: ğŸ”º
    numeric: 12
  - name: KING
    symbol: ğŸ‘‘
    numeric: 13
  - name: ACE
    symbol: A
    numeric: 14
symbols:
  __PREFIX__: ""
  __SUFFIX__: ""
  __DELIMITER__: ""
